name: Run python job
on: 
    push:
        branches:
            - main

jobs:
    Ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            -name: Checkout code
             uses: actions/checkout@v2

            -name: Print Message
             run: echo 'Welcome to AVD'