name: Run python program
on: 
    push:
        branches:
            - main

jobs:
    Ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            -name:Checkout code
             uses: actions/checkout@v2

            -name:print welcome meassage
             run: echo "Welcome to git hub actions"